export const DISPATCH_ACTION = {
    PROJECT_LOADED: "PROJECT_LOADED",
    WEEK_LENGTH_CHANGED: "WEEK_LENGTH_CHANGED",
    START_CHANGED: "START_CHANGED",
    ADJUST: "ADJUST",
    IGNORE_PROJECT_TOGGLE: "IGNORE_PROJECT_TOGGLE",
    ROUNDING_CHANGED: "ROUNDING_CHANGED",
    ORDER_CHANGED: "ORDER_CHANGED",
}

export const DEFAULT_ADJUSTMENT = 1