export const DISPATCH_ACTION = {
    "PROJECT_LOADED": "PROJECT_LOADED",
    "WEEK_LENGTH_CHANGED": "WEEK_LENGTH_CHANGED",
    "START_CHANGED": "START_CHANGED",
    "ADJUST": "ADJUST",
    "ROUNDING_CHANGED": "ROUNDING_CHANGED",
}

export const DEFAULT_ADJUSTMENT = 1